services:
  - type: web
    name: vctm-erp-attendance-academic-system
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
